{
    "docs": "https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/ignores.html", 
    "results": [
        {
            "message": "The test `ansible-test sanity --test ignores` [[explain](https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/ignores.html)] failed with 82 errors:", 
            "output": "tests/sanity/ignore-2.10.txt:3:1: Duplicate 'action-plugin-docs' ignore for path 'plugins/action/aruba.py' first found on line 2\ntests/sanity/ignore-2.10.txt:5:1: Duplicate 'action-plugin-docs' ignore for path 'plugins/action/ce.py' first found on line 4\ntests/sanity/ignore-2.10.txt:7:1: Duplicate 'action-plugin-docs' ignore for path 'plugins/action/cnos.py' first found on line 6\ntests/sanity/ignore-2.10.txt:9:1: Duplicate 'action-plugin-docs' ignore for path 'plugins/action/enos.py' first found on line 8\ntests/sanity/ignore-2.10.txt:11:1: Duplicate 'action-plugin-docs' ignore for path 'plugins/action/ironware.py' first found on line 10\ntests/sanity/ignore-2.10.txt:14:1: Duplicate 'action-plugin-docs' ignore for path 'plugins/action/sros.py' first found on line 13\ntests/sanity/ignore-2.10.txt:104:1: File 'plugins/modules/cloud/cloudstack/cs_network.py' does not exist\ntests/sanity/ignore-2.10.txt:105:1: File 'plugins/modules/cloud/cloudstack/cs_network_acl_rule.py' does not exist\ntests/sanity/ignore-2.10.txt:106:1: File 'plugins/modules/cloud/cloudstack/cs_network_offering.py' does not exist\ntests/sanity/ignore-2.10.txt:107:1: File 'plugins/modules/cloud/cloudstack/cs_physical_network.py' does not exist\ntests/sanity/ignore-2.10.txt:108:1: File 'plugins/modules/cloud/dimensiondata/dimensiondata_network.py' does not exist\ntests/sanity/ignore-2.10.txt:109:1: File 'plugins/modules/cloud/dimensiondata/dimensiondata_network.py' does not exist\ntests/sanity/ignore-2.10.txt:110:1: File 'plugins/modules/cloud/dimensiondata/dimensiondata_network.py' does not exist\ntests/sanity/ignore-2.10.txt:111:1: File 'plugins/modules/cloud/google/gcp_compute_network_info.py' does not exist\ntests/sanity/ignore-2.10.txt:112:1: File 'plugins/modules/cloud/google/gcp_compute_network_info.py' does not exist\ntests/sanity/ignore-2.10.txt:113:1: File 'plugins/modules/cloud/google/gcp_compute_subnetwork_info.py' does not exist\ntests/sanity/ignore-2.10.txt:114:1: File 'plugins/modules/cloud/google/gcp_compute_subnetwork_info.py' does not exist\ntests/sanity/ignore-2.10.txt:115:1: File 'plugins/modules/cloud/oneandone/oneandone_private_network.py' does not exist\ntests/sanity/ignore-2.10.txt:116:1: File 'plugins/modules/cloud/oneandone/oneandone_private_network.py' does not exist\ntests/sanity/ignore-2.10.txt:117:1: File 'plugins/modules/cloud/oneandone/oneandone_private_network.py' does not exist\ntests/sanity/ignore-2.10.txt:118:1: File 'plugins/modules/cloud/oneandone/oneandone_private_network.py' does not exist\ntests/sanity/ignore-2.10.txt:119:1: File 'plugins/modules/cloud/oneandone/oneandone_private_network.py' does not exist\ntests/sanity/ignore-2.10.txt:120:1: File 'plugins/modules/cloud/rackspace/rax_network.py' does not exist\ntests/sanity/ignore-2.10.txt:121:1: File 'plugins/modules/cloud/rackspace/rax_network.py' does not exist\ntests/sanity/ignore-2.10.txt:122:1: File 'plugins/modules/cloud/rackspace/rax_network.py' does not exist\ntests/sanity/ignore-2.10.txt:123:1: File 'plugins/modules/cloud/rackspace/rax_network.py' does not exist\ntests/sanity/ignore-2.10.txt:124:1: File 'plugins/modules/cloud/vultr/vultr_network.py' does not exist\ntests/sanity/ignore-2.10.txt:125:1: File 'plugins/modules/cloud/vultr/vultr_network_facts.py' does not exist\ntests/sanity/ignore-2.10.txt:126:1: File 'plugins/modules/cloud/vultr/vultr_network_info.py' does not exist\ntests/sanity/ignore-2.10.txt:127:1: File 'plugins/modules/net_tools/nios/nios_network.py' does not exist\ntests/sanity/ignore-2.10.txt:128:1: File 'plugins/modules/net_tools/nios/nios_network.py' does not exist\ntests/sanity/ignore-2.10.txt:129:1: File 'plugins/modules/net_tools/nios/nios_network.py' does not exist\ntests/sanity/ignore-2.10.txt:130:1: File 'plugins/modules/net_tools/nios/nios_network.py' does not exist\ntests/sanity/ignore-2.10.txt:131:1: File 'plugins/modules/net_tools/nios/nios_network.py' does not exist\ntests/sanity/ignore-2.10.txt:132:1: File 'plugins/modules/net_tools/nios/nios_network.py' does not exist\ntests/sanity/ignore-2.10.txt:133:1: File 'plugins/modules/net_tools/nios/nios_network.py' does not exist\ntests/sanity/ignore-2.10.txt:134:1: File 'plugins/modules/net_tools/nios/nios_network_view.py' does not exist\ntests/sanity/ignore-2.10.txt:135:1: File 'plugins/modules/net_tools/nios/nios_network_view.py' does not exist\ntests/sanity/ignore-2.10.txt:136:1: File 'plugins/modules/net_tools/nios/nios_network_view.py' does not exist\ntests/sanity/ignore-2.10.txt:137:1: File 'plugins/modules/net_tools/nios/nios_network_view.py' does not exist\ntests/sanity/ignore-2.10.txt:138:1: File 'plugins/modules/net_tools/nios/nios_network_view.py' does not exist\ntests/sanity/ignore-2.10.txt:139:1: File 'plugins/modules/net_tools/nios/nios_network_view.py' does not exist\ntests/sanity/ignore-2.10.txt:1682:1: File 'plugins/modules/remote_management/oneview/oneview_ethernet_network.py' does not exist\ntests/sanity/ignore-2.10.txt:1683:1: File 'plugins/modules/remote_management/oneview/oneview_ethernet_network.py' does not exist\ntests/sanity/ignore-2.10.txt:1684:1: File 'plugins/modules/remote_management/oneview/oneview_ethernet_network_info.py' does not exist\ntests/sanity/ignore-2.10.txt:1685:1: File 'plugins/modules/remote_management/oneview/oneview_ethernet_network_info.py' does not exist\ntests/sanity/ignore-2.10.txt:1686:1: File 'plugins/modules/remote_management/oneview/oneview_ethernet_network_info.py' does not exist\ntests/sanity/ignore-2.10.txt:1687:1: File 'plugins/modules/remote_management/oneview/oneview_fc_network.py' does not exist\ntests/sanity/ignore-2.10.txt:1688:1: File 'plugins/modules/remote_management/oneview/oneview_fc_network.py' does not exist\ntests/sanity/ignore-2.10.txt:1689:1: File 'plugins/modules/remote_management/oneview/oneview_fc_network.py' does not exist\ntests/sanity/ignore-2.10.txt:1690:1: File 'plugins/modules/remote_management/oneview/oneview_fc_network.py' does not exist\ntests/sanity/ignore-2.10.txt:1691:1: File 'plugins/modules/remote_management/oneview/oneview_fc_network_info.py' does not exist\ntests/sanity/ignore-2.10.txt:1692:1: File 'plugins/modules/remote_management/oneview/oneview_fc_network_info.py' does not exist\ntests/sanity/ignore-2.10.txt:1693:1: File 'plugins/modules/remote_management/oneview/oneview_fcoe_network.py' does not exist\ntests/sanity/ignore-2.10.txt:1694:1: File 'plugins/modules/remote_management/oneview/oneview_fcoe_network.py' does not exist\ntests/sanity/ignore-2.10.txt:1695:1: File 'plugins/modules/remote_management/oneview/oneview_fcoe_network.py' does not exist\ntests/sanity/ignore-2.10.txt:1696:1: File 'plugins/modules/remote_management/oneview/oneview_fcoe_network_info.py' does not exist\ntests/sanity/ignore-2.10.txt:1697:1: File 'plugins/modules/remote_management/oneview/oneview_fcoe_network_info.py' does not exist\ntests/sanity/ignore-2.10.txt:1698:1: File 'plugins/modules/remote_management/oneview/oneview_network_set.py' does not exist\ntests/sanity/ignore-2.10.txt:1699:1: File 'plugins/modules/remote_management/oneview/oneview_network_set.py' does not exist\ntests/sanity/ignore-2.10.txt:1700:1: File 'plugins/modules/remote_management/oneview/oneview_network_set.py' does not exist\ntests/sanity/ignore-2.10.txt:1701:1: File 'plugins/modules/remote_management/oneview/oneview_network_set_info.py' does not exist\ntests/sanity/ignore-2.10.txt:1702:1: File 'plugins/modules/remote_management/oneview/oneview_network_set_info.py' does not exist\ntests/sanity/ignore-2.10.txt:1703:1: File 'plugins/modules/remote_management/oneview/oneview_network_set_info.py' does not exist\ntests/sanity/ignore-2.10.txt:1704:1: File 'plugins/modules/web_infrastructure/sophos_utm/utm_network_interface_address.py' does not exist\ntests/sanity/ignore-2.10.txt:1705:1: File 'plugins/modules/web_infrastructure/sophos_utm/utm_network_interface_address_info.py' does not exist\ntests/sanity/ignore-2.10.txt:1793:1: File 'tests/unit/modules/remote_management/oneview/test_oneview_ethernet_network.py' does not exist\ntests/sanity/ignore-2.10.txt:1794:1: File 'tests/unit/modules/remote_management/oneview/test_oneview_ethernet_network.py' does not exist\ntests/sanity/ignore-2.10.txt:1795:1: File 'tests/unit/modules/remote_management/oneview/test_oneview_ethernet_network_info.py' does not exist\ntests/sanity/ignore-2.10.txt:1796:1: File 'tests/unit/modules/remote_management/oneview/test_oneview_ethernet_network_info.py' does not exist\ntests/sanity/ignore-2.10.txt:1797:1: File 'tests/unit/modules/remote_management/oneview/test_oneview_fc_network.py' does not exist\ntests/sanity/ignore-2.10.txt:1798:1: File 'tests/unit/modules/remote_management/oneview/test_oneview_fc_network.py' does not exist\ntests/sanity/ignore-2.10.txt:1799:1: File 'tests/unit/modules/remote_management/oneview/test_oneview_fc_network_info.py' does not exist\ntests/sanity/ignore-2.10.txt:1800:1: File 'tests/unit/modules/remote_management/oneview/test_oneview_fc_network_info.py' does not exist\ntests/sanity/ignore-2.10.txt:1801:1: File 'tests/unit/modules/remote_management/oneview/test_oneview_fcoe_network.py' does not exist\ntests/sanity/ignore-2.10.txt:1802:1: File 'tests/unit/modules/remote_management/oneview/test_oneview_fcoe_network.py' does not exist\ntests/sanity/ignore-2.10.txt:1803:1: File 'tests/unit/modules/remote_management/oneview/test_oneview_fcoe_network_info.py' does not exist\ntests/sanity/ignore-2.10.txt:1804:1: File 'tests/unit/modules/remote_management/oneview/test_oneview_fcoe_network_info.py' does not exist\ntests/sanity/ignore-2.10.txt:1805:1: File 'tests/unit/modules/remote_management/oneview/test_oneview_network_set.py' does not exist\ntests/sanity/ignore-2.10.txt:1806:1: File 'tests/unit/modules/remote_management/oneview/test_oneview_network_set.py' does not exist\ntests/sanity/ignore-2.10.txt:1807:1: File 'tests/unit/modules/remote_management/oneview/test_oneview_network_set_info.py' does not exist\ntests/sanity/ignore-2.10.txt:1808:1: File 'tests/unit/modules/remote_management/oneview/test_oneview_network_set_info.py' does not exist"
        }
    ], 
    "verified": false
}
